What is numpy?
NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.

At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types

Numpy Arrays Vs Python Sequences
NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4])


In [3]:
print(a)

[1 2 3 4]


In [4]:
print(type(a))

<class 'numpy.ndarray'>


In [5]:
# 2D numpy array
b = np.array([[1,2,3],[4,5,6]])


In [6]:
print(b)

[[1 2 3]
 [4 5 6]]


In [7]:
# 3D array

c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [8]:
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [9]:
# Data Types

np.array([1,2,3,4],dtype=bool)

array([ True,  True,  True,  True])

In [10]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [12]:
# reshape

In [13]:
np.arange(1,11).reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [14]:
np.arange(1,13).reshape(2,2,3)

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [15]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [16]:
np.zeros((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [17]:
np.random.random((3,4))

array([[0.30745744, 0.30319693, 0.04707042, 0.16418872],
       [0.60708068, 0.832601  , 0.3604903 , 0.70193676],
       [0.17436948, 0.74767421, 0.22890254, 0.40705509]])

In [18]:
np.linspace(-10,10,10,dtype=int)

array([-10,  -8,  -6,  -4,  -2,   1,   3,   5,   7,  10])

In [19]:
np.linspace(1,10,20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [20]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
# Numpy Attributes

In [22]:
a1= np.arange(10)

In [23]:
a2 = np.arange(12,dtype=float).reshape(3,4)

In [24]:
a3 = np.arange(8).reshape(2,2,2)

In [25]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
# No of Dimensions

In [27]:
a1.ndim

1

In [28]:
a1.shape

(10,)

In [29]:
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [30]:
a2.ndim

2

In [31]:
a2.shape

(3, 4)

In [32]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [33]:
a3.ndim

3

## 

In [34]:
print(a3.shape)

(2, 2, 2)


In [35]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [36]:
a3.size

8

In [37]:
a2.size

12

In [38]:
a1.size

10

In [39]:
a1.itemsize

4

In [40]:
a2.itemsize

8

In [41]:
print(a2.dtype)

float64


In [42]:
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [43]:
a3.itemsize

4

In [44]:
print(a1.dtype)

int32


In [45]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
# Array Operations

In [47]:
a1= np.arange(12).reshape(3,4)

In [48]:
a2= np.arange(12,24).reshape(3,4)

In [49]:
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [50]:
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [51]:
# Scalar Operations

In [52]:
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [53]:
a1-2

array([[-2, -1,  0,  1],
       [ 2,  3,  4,  5],
       [ 6,  7,  8,  9]])

In [54]:
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [55]:
a2==15

array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [56]:
# Vector Operations

In [57]:
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [58]:
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [59]:
a1*a2

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

In [60]:
# Functions

In [61]:
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [62]:
np.max(a2,0)

array([20, 21, 22, 23])

In [63]:
np.min(a2)

12

In [64]:
np.sum(a2)

210

In [65]:
np.prod(a2,axis=0)

array([3840, 4641, 5544, 6555])

In [66]:
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [67]:
np.mean(a2,axis=0)

array([16., 17., 18., 19.])

In [68]:
np.median(a2,axis=1)

array([13.5, 17.5, 21.5])

In [69]:
np.std(a2)

3.452052529534663

In [70]:
np.var(a2)

11.916666666666666

In [71]:
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [72]:
np.sin(a2)

array([[-0.53657292,  0.42016704,  0.99060736,  0.65028784],
       [-0.28790332, -0.96139749, -0.75098725,  0.14987721],
       [ 0.91294525,  0.83665564, -0.00885131, -0.8462204 ]])

In [73]:
# Dot Product

In [74]:
a2= np.arange(12).reshape(3,4)

In [75]:
a3= np.arange(12,24).reshape(4,3)

In [76]:
np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [77]:
np.round(np.random.random((3,4))*100)

array([[79., 56., 53., 46.],
       [85., 95., 36.,  2.],
       [ 6., 51., 31., 24.]])

In [78]:
np.floor(np.random.random((3,4))*100)

array([[61., 61., 41., 61.],
       [54.,  3., 77., 67.],
       [45., 19., 30., 33.]])

In [79]:
np.ceil(np.random.random((3,4))*100)

array([[20., 20., 22., 10.],
       [86., 42., 46., 63.],
       [20., 37., 92., 81.]])

In [80]:
# Indexing and Slicing

In [81]:
a1 = np.arange(10)

In [82]:
a2 = np.arange(12).reshape(3,4)

In [83]:
a3 = np.arange(8).reshape(2,2,2)

In [84]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [85]:
a1[-1]

9

In [86]:
a1[3]

3

In [87]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [88]:
a2[1,0]

4

In [89]:
a2[1,2]

6

In [90]:
a2[1][2]

6

In [91]:
a2[2,3]

11

In [92]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [93]:
a3[1,1,0]

6

In [94]:
a3[0,0,0]

0

In [95]:
a3[1,0,1]

5

In [96]:
a3[0,1,0]

2

In [97]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [98]:
a1[2:5]

array([2, 3, 4])

In [99]:
a1[2:5:2]

array([2, 4])

In [100]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [101]:
a2[1,::3]

array([4, 7])

In [102]:
a2[0:2,1:]

array([[1, 2, 3],
       [5, 6, 7]])

In [103]:
a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [104]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [105]:
a2[0,:]

array([0, 1, 2, 3])

In [106]:
a2[:,2]

array([ 2,  6, 10])

In [107]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [108]:
a3 = np.arange(27).reshape(3,3,3)

In [109]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [110]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

In [111]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [112]:
a3[1,:,1]

array([10, 13, 16])

In [113]:
a3[0,1,:]

array([3, 4, 5])

In [114]:
a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [115]:
a3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [116]:
a1   

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [120]:
for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [117]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [122]:
for i in a2:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [118]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [123]:
for i in a3:
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [124]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [125]:
for i in np.nditer(a3):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


In [126]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [128]:
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [127]:
np.transpose(a2)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [129]:
# STACKING

In [130]:
a4 = np.arange(12).reshape(3,4)

In [134]:
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [131]:
a5 = np.arange(12,24).reshape(3,4)

In [135]:
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [137]:
np.hstack((a4,a5,a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15,  0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19,  4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23,  8,  9, 10, 11, 20, 21, 22, 23]])

In [140]:
np.vstack((a4,a5,a4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [141]:
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [144]:
np.hsplit(a4,5)

ValueError: array split does not result in an equal division

In [143]:
np.hsplit(a4,4)

[array([[0],
        [4],
        [8]]),
 array([[1],
        [5],
        [9]]),
 array([[ 2],
        [ 6],
        [10]]),
 array([[ 3],
        [ 7],
        [11]])]

In [142]:
np.hsplit(a4,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [145]:
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [146]:
np.vsplit(a5,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]

In [147]:
np.vsplit(a5,2)

ValueError: array split does not result in an equal division

In [148]:
a = [i for i in range (10000000)]

b = [i for i in range(10000000,20000000)]

c = []

import time

start = time.time()

for i in range(len(a)):
    c.append(a[i]+b[i])
    
print(time.time()-start)
    

6.731566905975342


In [149]:
import numpy as np

In [150]:
a = np.arange(10000000)

b = np.arange(10000000,20000000)

start = time.time()
c = a+b 

print(time.time()-start)

0.28155970573425293


In [151]:
6.73/0.28

24.035714285714285

In [152]:
# Fancy Index

In [154]:
a = np.arange(12).reshape(4,3)

In [155]:
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [156]:
a[1,2]

5

In [157]:
a[1:3,1:3]

array([[4, 5],
       [7, 8]])

In [158]:
a[::2]

array([[0, 1, 2],
       [6, 7, 8]])

In [159]:
a[[0,2,3]]

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [162]:
b = np.arange(24).reshape(6,4)

In [163]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [164]:
a[[0,2,3,5]]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [20, 21, 22, 23]])

In [165]:
a[:,[0,2,3]]

array([[ 0,  2,  3],
       [ 4,  6,  7],
       [ 8, 10, 11],
       [12, 14, 15],
       [16, 18, 19],
       [20, 22, 23]])

In [166]:
# Boolean Indexing

In [169]:
a = np.random.randint(1,100,24).reshape(6,4)
a

array([[83, 17, 70, 61],
       [92, 72, 83, 49],
       [81, 79, 49, 78],
       [38,  4,  5, 51],
       [63, 92, 32, 44],
       [48, 91, 61, 40]])

In [170]:
# Find all numbers greater then 50

In [171]:
a>50

array([[ True, False,  True,  True],
       [ True,  True,  True, False],
       [ True,  True, False,  True],
       [False, False, False,  True],
       [ True,  True, False, False],
       [False,  True,  True, False]])

In [172]:
a[a>50]

array([83, 70, 61, 92, 72, 83, 81, 79, 78, 51, 63, 92, 91, 61])

In [173]:
# Find out even numbers

In [174]:
a

array([[83, 17, 70, 61],
       [92, 72, 83, 49],
       [81, 79, 49, 78],
       [38,  4,  5, 51],
       [63, 92, 32, 44],
       [48, 91, 61, 40]])

In [176]:
a[a%2==0]

array([70, 92, 72, 78, 38,  4, 92, 32, 44, 48, 40])

In [177]:
# Find all numbers greater then 50 and are even 

In [180]:
a[(a>50) & (a%2==0)]

array([70, 92, 72, 78, 92])