In [3]:
import numpy as np

In [4]:
a = np.array([1,2,3,4,5,6])
print(a)
print(type(a))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [5]:
# 2D array
b = np.array([[1,2,3],[4,5,6]])
print(b) #matrix

[[1 2 3]
 [4 5 6]]


In [24]:
c = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(c)
c.shape


[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


(1, 3, 3)

In [19]:
d = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(d)  #tensor

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [8]:
np.array([1,2,3,4],dtype = float)

array([1., 2., 3., 4.])

In [9]:
np.array([1,2,3,4],dtype = bool)

array([ True,  True,  True,  True])

In [25]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [28]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [35]:
np.arange(1,11).reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [36]:
np.arange(1,13).reshape(2,2,3)

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [37]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [38]:
np.zeros((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [42]:
np.random.random((3,4))

array([[0.53924598, 0.04116328, 0.22905536, 0.1600539 ],
       [0.72934274, 0.48536671, 0.42729738, 0.59064708],
       [0.24233783, 0.77937033, 0.63448912, 0.7097869 ]])

In [44]:
np.linspace(-10,10,10,dtype=int)

array([-10,  -8,  -6,  -4,  -2,   1,   3,   5,   7,  10])

In [45]:
np.linspace(1,10,15)

array([ 1.        ,  1.64285714,  2.28571429,  2.92857143,  3.57142857,
        4.21428571,  4.85714286,  5.5       ,  6.14285714,  6.78571429,
        7.42857143,  8.07142857,  8.71428571,  9.35714286, 10.        ])

In [48]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [60]:
a1 = np.arange(10)
a1




array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [53]:
a2 = np.arange(12,dtype=float).reshape(3,4)
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [54]:
a3 = np.arange(8).reshape(2,2,2)
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [62]:
a2.ndim

2

In [63]:
a3.ndim

3

#Vector operations

In [10]:
a1 = np.arange(10)
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [12]:
a2 = np.arange(12).reshape(3,4)
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [13]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [14]:
for i in a2:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [15]:
for i in a3:
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [16]:
for i in np.nditer(a3):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
